<?php
/**
 * @category   Apptrian
 * @package    Apptrian_SocialIntegrator
 * @author     Apptrian
 * @copyright  Copyright (c) 2015 Apptrian (http://www.apptrian.com)
 * @license    http://www.apptrian.com/license    Proprietary Software License (EULA)
 */

    if (Mage::getStoreConfig('apptrian_socialintegrator/general/include_fbjssdk')): ?>
    
    <!-- Facebook JavaScript SDK -->
    <div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode() ?>/sdk.js#xfbml=1&version=v2.3";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
    
<?php endif; ?>

<?php if (Mage::getStoreConfig('apptrian_socialintegrator/general/include_injs')): ?>
    
    <!-- Linkedin in.js -->
    <script src="//platform.linkedin.com/in.js" type="text/javascript">
        lang: <?php echo Mage::app()->getLocale()->getLocaleCode(); ?>
    </script>
    
<?php endif; ?>

